from PyQt6.QtWidgets import*
def pokaz_novun():
    window = QDialog()
    mainline = QVBoxLayout()
    h1 = QHBoxLayout()
    h2 = QHBoxLayout()
    lab = QLabel("Якого часу новини?(години,хвилини)")
    tex = QLineEdit()
    lab2 = QLabel("Новини якого регіону? (писати: ua,us...)")
    tex2 = QLineEdit()
    ag = QLabel("Можливі країни:")
    ua = QLabel("Україна (ua)")
    us = QLabel("Америка (us)")
    gb = QLabel("Великрбританія (gb)")
    br = QLabel("Бразилія (br)")
    fr = QLabel("Франія (fr)")
    mainline.addWidget(lab)
    mainline.addWidget(tex)
    mainline.addWidget(lab2)
    mainline.addWidget(tex2)
    mainline.addWidget(ag)
    h1.addWidget(ua)
    h1.addWidget(us)
    h2.addWidget(gb)
    h2.addWidget(br)
    h2.addWidget(fr)
    mainline.addLayout(h1)
    mainline.addLayout(h2)

    window.setLayout(mainline)
    window.show()
    window.exec()

