import requests
from PyQt6.QtWidgets import*
from zaput import*
def pokaz_novun():
    window = QDialog()
    mainline = QVBoxLayout()
    v1 = QVBoxLayout()
    h1 = QHBoxLayout()
    h2 = QHBoxLayout()
    lab = QLabel("Якого часу новини?(години = число,хвилини = число хв)")
    tex = QLineEdit()
    lab2 = QLabel("Новини якого регіону? (писати: ua,us...)")
    tex2 = QLineEdit()
    ag = QLabel("Можливі країни:")
    ua = QLabel("Україна (ua)")
    us = QLabel("Америка (us)")
    gb = QLabel("Великрбританія (gb)")
    br = QLabel("Бразилія (br)")
    fr = QLabel("Франія (fr)")
    k1 = QPushButton("Далі")
    mainline.addWidget(lab)
    mainline.addWidget(tex)
    mainline.addWidget(lab2)
    mainline.addWidget(tex2)
    mainline.addWidget(ag)
    h1.addWidget(ua)
    h1.addWidget(us)
    h2.addWidget(gb)
    h2.addWidget(br)
    h2.addWidget(fr)
    v1.addWidget(k1)
    h2.addLayout(v1)
    mainline.addLayout(h1)
    mainline.addLayout(h2)

    k1.clicked.connect(novun)
    window.setLayout(mainline)
    window.show()
    window.exec()

